### ISSUE TITLE
M: change viz colors for HRRR smoke

### ISSUE THREAD

**Issue by cshartsough** [NOAA-GSL/pygraf#144]
Ravan has requested that the highest visibility values be true white. They are currently tan-ish to match the MDL color scheme, per a request from @terraladwig et al. Here's an [example](https://rapidrefresh.noaa.gov/hrrr/HRRRsmoke/displayMapUpdated.cgi?keys=hrrr_ncep_jet:&runtime=2022031420&plot_type=vis_full_sfc&fcst=000&time_inc=60&num_times=49&model=hrrr&ptitle=HRRR-Smoke%20Graphics&maxFcstLen=48&fcstStrLen=-1&domain=full&adtfn=1).

**Comment by christinaholtNOAA** [comment]
Overcome by new requests with merged PR #174
